version: '3.8'

services:
  db:
    image: postgres
    container_name: postgres-zup
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=zupdesafio
    ports:
      - 5432:5432
    restart: always
    networks: # Specify the networks for this service
      - outside-nw
      - internal-nw

  api:
    image: api-zup
    container_name: api-zup
    build: ./
    ports:
      - 8080:8080
    restart: always
    stdin_open: true
    tty: true
    depends_on:
      - db
    links:
      - db:db
    environment:
      - JAEGER_SERVICE_NAME=hello_service
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6831
      - JAEGER_SAMPLER_MANAGER_HOST_PORT=jaeger:5778
    networks: # Specify the networks for this service
      - outside-nw
      - internal-nw

  jaeger:
    image: jaegertracing/all-in-one:1.7
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
    networks: # Specify the networks for this service
      - outside-nw
      - internal-nw

networks:
  internal-nw:
    internal: true
  outside-nw: